### ISSUE TITLE
Links under "Related Info" ending in "Not found"

### ISSUE THREAD

**Issue by rothandreas** [SAP-docs/btp-custom-domain-service#5]
All three Links under "Related Info" ending in "Not found"

**Comment by Prasihub** [comment]
@rothandreas - Hello, could you please tell me which topic you are referring to? Thank you!

**Comment by rothandreas** [comment]
Hi, thanks for the Quick response and sorry for the missing Detail. just rechecked and Issue is gone. I think there was a big clinch on the help Page
